from persons import *
sonny = Person('Sonny', 'sonny@hotmail.com', '777-777-7777')
jordan = Person('Jordan', 'jordan@gmail.com', '555-555-5555')
daria = Person('Daria', 'daria@yahoo.com', '444-555-6666')
sonny.greet(jordan)
jordan.greet(sonny)
sonny.greet(daria)
sonny.printContact()
jordan.printContact()
sonny.addFriend(jordan)
jordan.addFriend(sonny)
sonny.countFriends()
jordan.countFriends()
sonny.peopleMet()
jordan.peopleMet()