theWord = raw_input('Enter a word here: ')
theWord = theWord.replace("AA", "AAAAA")
theWord = theWord.replace("EE", "EEEEE")
theWord = theWord.replace("II", "IIIII")
theWord = theWord.replace("OO", "OOOOO")
theWord = theWord.replace("UU", "UUUUU")
theWord = theWord.replace("aa", "aaaaa")
theWord = theWord.replace("ee", "eeeee")
theWord = theWord.replace("ii", "iiiii")
theWord = theWord.replace("oo", "ooooo")
theWord = theWord.replace("uu", "uuuuu")
print theWord